apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 587312347089.dkr.ecr.us-east-1.amazonaws.com/webapp-image:v0.1
    env:
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: APP_COLOR
      value: "blue"
    - name: DBPORT
      value: "3306"
    - name: DBHOST
      value: 10.244.0.24
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: regcred