apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sql-replica
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqldb
        image: 587312347089.dkr.ecr.us-east-1.amazonaws.com/mysql-image:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: regcred